# Generated by Django 2.2.6 on 2019-10-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191028_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='menus',
            new_name='menu',
        ),
        migrations.AlterField(
            model_name='base',
            name='slices',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
