# Generated by Django 2.2.6 on 2019-10-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_extra_filling_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='orders.Menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub',
            name='filling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Filling'),
        ),
    ]
