# Generated by Django 2.2.6 on 2019-11-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191028_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='orders.Base'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Menu'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='filling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='orders.Filling'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Menu'),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('LG', 'Large'), ('SM', 'Small')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other', to='orders.Menu')),
            ],
        ),
    ]
