# Generated by Django 2.2.6 on 2019-11-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191103_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='size',
            field=models.CharField(choices=[('LG', 'Large'), ('SM', 'Small'), ('', 'N/A')], max_length=2),
        ),
    ]
